### PR TITLE
TSS-12 TSS-13: smaller font size for basic cards and added rule for t…

### PR DESCRIPTION
**Pull request by jenbreese**
…he shuttle cards

#  READY FOR REVIEW

# Summary
- Reduced  the `h3` on the cards to a smaller font size `font-size: 1.2em;`
- Added the line like the current prod site. `border-bottom: 1px solid #dad7cb;`
- Added additional spacing after the line to balance it out.

# Review By (Date)
- 10/7

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. 3. Open Gitpod
4. copy this page: https://transportationd9-test.sites.stanford.edu/marguerite
6. Create the shared tag of `marguerite-shuttle`.
5. You need to create basic pages with a shared tag of `marguerite-shuttle`. on the page put content into the meta description for the cards to have it.
7. add a list of the cards
4. If the previous PR is merged then you will see the equal heights.
5. You should see the line and the `h3` at a smaller font size.
6. You should see an even space after the line  and before the content. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- TSS-12](https://stanfordits.atlassian.net/browse/TSS-12)
[- TSS-13](https://stanfordits.atlassian.net/browse/TSS-13)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by rebeccahongsf — APPROVED** [review]
LGTM 🚀 

image

**Comment by buttonwillowsix** [comment]
@jenbreese we were having a convo with Kerri about scaling typography on Stanford Sites (and also word-break settings.) I think this solution is great for this moment/client, but if you have any thoughts about how we should treat this stuff going forward, I'd love to hear it!

**Comment by buttonwillowsix** [comment]
I am not seeing the smaller font or line in @rebeccahongsf 's screenshot?

**Comment by jenbreese** [comment]
I agree. I don't see it in the screenshot either.  I think itis because I didn't update the details. Doh. Let me fix it up and look again.

**Comment by jenbreese** [comment]
@buttonwillowsix If you wanted to take a look, I updated the PR and you can see the font size change and the line.

**Review by buttonwillowsix — APPROVED** [review]
Screenshot 2024-10-07 at 11 07 30 AM
I see lines and smaller fonts! Yay!

**Pull request merged**
