### PR TITLE
TSS-58: added color for the 1050 line

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Added color and flag for the 1050 Arastradero line 

# Review By (Date)
- When time

# Criticality
- Normal

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this GitPod
3. Navigate to `/marguerite/1050a`
4. Add the metadata -> Page Description `Travels between Li Ka Shing Center, Porter Dr, Hillview Ave, and Arastradero Rd.`
5. Add the `Marguerite Shuttle` to the taxonomy
6. update the list page to have enough cards display on the list.  `/getting-around-stanford/marguerite-shuttle/shuttle-lines-and-schedules`
7. Verify it has the brown line on the card and the brown flag. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- TSS-58](https://stanfordits.atlassian.net/browse/TSS-58)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by rebeccahongsf — COMMENTED** [review]
@jenbreese I think I might be missing a step 🤔 

I added the metadata and taxonomy shared tag to the 1050 Arastredero but was unable to get the brown line to display. I tried rebuilding the styles just in case but no avail. When searching for `flag-mark--brown` only `flag-mark--brown-green` appeared on the page. 

Any thoughts on what might be missing or perhaps something I can do to get my gitpod preview working?

image

**Comment by jenbreese** [comment]
@rebeccahongsf That's super weird.  You have the Line S with the brown flag and it is appearing yellow.  I'm building to check it out.

**Comment by jenbreese** [comment]
So the problem is the word `Arastradero`.  It needs to match for it to work. Try changing the title of the page on your build.

**Review by rebeccahongsf — APPROVED** [review]
Ooo that did the trick! Thank you, Jen! This PR looks great to me 🚀 
image

**Pull request merged**
